export const ROUTER_URL = {
  HOME: "/",

  MENU: `/menu`,
  STORE: `/stores`,
  ABOUT: `/about`,
  CONTACT: `/contact`,
  VERSION: `/version`,

  CLIENT: `/client`,
  CLIENT_ROUTER: {
    REGISTER: `/client/register`,
    LOGIN: `/client/login`,
    PROFILE: `/client/profile`,
    FORGOT_PASSWORD: `/client/forgot-password`,
    CART: `cart`,
    ORDER: `order`,
    PAYMENT: `payment`,
    CHECKOUT: `checkout`,
    PRODUCTS: `products`,
    CATEGORIES: `categories`,
  },

  ADMIN: `/admin`,
  ADMIN_ROUTER: {
    LOGIN: `/admin/login`,
    FORGOT_PASSWORD: `/admin/forgot-password`,
    PROFILE: `profile`,
    DASHBOARD: `dashboard`,
    USER: `users`,
    CATEGORY: `categories`,
    PRODUCT: `products`,
    ORDER: `orders`,
    FRANCHISE: `franchises`,
    CUSTOMER: `customers`,
    CART: `cart`,
    LOYALTY: `loyalty`,
    PAYMENT: `payments`,
    INVENTORY: `inventory`,
  },
};
